import { Outfit } from 'next/font/google';

import { SlideProvider } from '@/components/slide-provider';

import './globals.css';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <SlideProvider>
        <body className={outfit.className}>{children}</body>
      </SlideProvider>
    </html>
  );
}
